# Generated by Django 6.0 on 2025-12-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('Technical', 'Technical'), ('Soft', 'Soft')], default='Technical', max_length=20),
        ),
    ]
