# Generated by Django 6.0 on 2025-12-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_achievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='resource_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
