# Generated by Django 6.0 on 2025-12-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_achievement_resource_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('issued_by', models.CharField(max_length=150)),
                ('issue_date', models.DateField()),
                ('resource_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
